[build]

# https://doc.rust-lang.org/cargo/reference/config.html
# https://doc.rust-lang.org/rustc/command-line-arguments.html

rustflags = ["-Lnative=/home/ljh/Documents/hello_rust/src/hello", "-ldylib=hello"]
